### ISSUE TITLE
[Bug Report] This happens when another thing should have

### ISSUE THREAD

**Issue by wysohn** [jmanpenilla/MiniMOTD#29]
**Server Software and Version:**
13:11:01 [INFO] Linux 4.15.0-122-generic [x64],
13:11:01 [INFO] Java 1.8.0_272 [x64],
13:11:01 [INFO] BungeeCord git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:9c078b7:1539,

---

Hello,

first of all, please refer to this issue: https://github.com/ME1312/SubServers-2/issues/56#issue-738556062

So basically, this plugin somehow does not work with SubServer, but I cannot find some easy reason why.

It works fine when used with bungeecord itself, but it only shows "Cannot connect to the server" when the bungeecord is running through SubServers.

Any idea?

**Comment by jmanpenilla** [comment]
I set the MOTD using the standard API, `ServerPing#setDescriptionComponent`, nothing out of the ordinary. I have no idea what is causing your issue and I do not know of or use SubServer. If MiniMOTD is working without SubServer but not with SubServer, I can only assume SubServer is causing the problem. I test MiniMOTD with [Waterfall](https://papermc.io/downloads#Waterfall), not BungeeCord, so it may be worth giving that a try, however I don't see how it would make a difference to be honest.

**Comment by ME1312** [comment]
I wouldn't exactly call `AdapterComponent` standard API. Anyway, after further investigation, the problem seems to be that your plugin is submitting a blank description object to BungeeCord when running alongside SubServers:
![whoops.jpg](https://i.postimg.cc/J023JNPF/cmd-Cb-Lyp-Tb-QMp.png)
`ping()` placed at the end of the event queue
`done()` placed at the equivalent of [here](https://github.com/SpigotMC/BungeeCord/blob/9c078b78c32863c59765e56d7e5164d0762ac563/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L257) in BungeeCord's code

Also, it seems to be running a duplicate event, which goes unused:
![x2.jpg](https://i.postimg.cc/LsCRFhXT/cmd-KW4u-Is0ftl.png)

**Comment by jmanpenilla** [comment]
> when running alongside SubServers

The implementation of the description component is irrelevant. MiniMOTD emits proper json and sets the description using the standard bungeecord api, as mentioned before.
Not sure what you are on about with this duplicate event either, the listener is only registered once.

In my opinion the most likely suspects in order here are
1. SubServers
2. Bungeecord
3. The adventure bungeecord platform adapter

If this issue is reproducible without SubServers I will look into it further. In that case, please open a new issue.
